src/Entity/Revenu.php
<?php

namespace App\Entity;

use App\Repository\RevenuRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=RevenuRepository::class)
 */
class Revenu
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $submit_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $denomination;

    /**
     * @ORM\Column(type="bigint")
	 * @Assert\GreaterThan(value=0, message="Entrer un montant superieur a zéro")
     */
    private $amount;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="revenus")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    public function __construct()
	{
		$this->submit_at = new \DateTime("now");
	}

	public function getId(): ?int
             {
                 return $this->id;
             }

    public function getSubmitAt(): ?\DateTimeInterface
    {
        return $this->submit_at;
    }

    public function setSubmitAt(\DateTimeInterface $submit_at): self
    {
        $this->submit_at = $submit_at;

        return $this;
    }

    public function getDenomination(): ?string
    {
        return $this->denomination;
    }

    public function setDenomination(string $denomination): self
    {
        $this->denomination = $denomination;

        return $this;
    }

    public function getAmount(): ?string
    {
        return $this->amount;
    }

    public function setAmount(string $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

src/Form/RevenuType.php
<?php

namespace App\Form;

use App\Entity\Revenu;
use DateTime;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RevenuType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('submit_at',DateType::class, [
				'widget' => 'single_text',
			])
            ->add('denomination')
            ->add('amount')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Revenu::class,
        ]);
    }
}

src/Controller/RevenuController.php
<?php

namespace App\Controller;

use App\Entity\OperationSearch;
use App\Entity\Revenu;
use App\Form\OperationSearchType;
use App\Form\RevenuType;
use App\Repository\RevenuRepository;
use Knp\Component\Pager\Pagination\PaginationInterface;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

/**
 * @Route("/revenu")
 * @IsGranted("IS_AUTHENTICATED_FULLY")
 */
class RevenuController extends AbstractController
{
	/**
	 * @Route("/", name="revenu_index", methods={"GET"})
	 * @param RevenuRepository $revenuRepository
	 * @param Security $security
	 * @param PaginatorInterface $paginator
	 * @param Request $request
	 * @return Response
	 */
    public function index(RevenuRepository $revenuRepository, Security $security, PaginatorInterface $paginator, Request $request):
	Response
    {
    	$revenus = $paginator->paginate(
    		$revenuRepository->getLatestQuery($security->getUser()),
			$request->get('page', 1)
		);
    	return $this->render('revenu/index.html.twig', [
    		'revenus' => $revenus,
			'active' => 'consultation'
		]);
    }

	/**
	 * @Route("/new", name="revenu_new", methods={"GET","POST"})
	 * @param Request $request
	 * @param Security $security
	 * @return Response
	 */
    public function new(Request $request, Security $security): Response
    {
        $revenu = new Revenu();
        $form = $this->createForm(RevenuType::class, $revenu);
        $form->handleRequest($request);
		$user = $security->getUser();
		$revenu->setUser($user);

		if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $user->setSolde(intval($user->getSolde() + $revenu->getAmount()));
            $entityManager->persist($revenu);
            $entityManager->flush();

			$this->addFlash("success", "Revenu crée");
			return $this->redirectToRoute('revenu_index');
        }

        return $this->render('revenu/new.html.twig', [
            'revenu' => $revenu,
            'form' => $form->createView(),
			'active' => 'new_consultation'
        ]);
    }

	/**
	 * @Route("/{id}", name="revenu_delete", methods={"DELETE"})
	 * @param Request $request
	 * @param Revenu $revenu
	 * @return Response
	 */
    public function delete(Request $request, Revenu $revenu): Response
    {
        if ($this->isCsrfTokenValid('delete'.$revenu->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($revenu);
            $entityManager->flush();
        }
		$this->addFlash("success", "Revenu supprimé");
        return $this->redirectToRoute('revenu_index');
    }
}

templates/revenu/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des revenus{% endblock %}

{% block body %}
    <div class="block-header">
        <div class="row clearfix">
            <div class="col-md-6 col-sm-12">
                <h2>Liste des revenus</h2>
            </div>
            <div class="col-md-6 col-sm-12 text-right hidden-xs">
                <a href="{{ path('revenu_new') }}" class="btn btn-sm btn-primary btn-round">Enregistrer un nouveau revenu</a>
            </div>
        </div>
    </div>
    {% for message in app.flashes("success") %}
        <div class="alert alert-success">{{ message }}</div>
    {% endfor %}
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12">
                <div class="table-responsive invoice_list mb-4">
                    <table class="table table-hover js-basic-example dataTable table-custom spacing8">
                        <thead>
                            <tr>
                                <th>Dénomination</th>
                                <th style="width: 50px;">Date</th>
                                <th style="width: 50px;">Montant</th>
                                <th style="width: 110px;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for revenu in revenus %}
                            <tr>

                                <td>{{ revenu.denomination }}</td>
                                <td>{{ revenu.submitAt ? revenu.submitAt|date('Y-m-d') : '' }}</td>
                                <td>{{ revenu.amount }}</td>
                                <td>
                                    <form method="post" action="{{ path('revenu_delete', {'id': revenu.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ revenu.id) }}">
                                        <button type="button" class="btn btn-sm btn-danger btn-default" title="Delete" data-toggle="tooltip" data-placement="top"><i class="icon-trash"></i></button>
                                    </form>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="5">Aucun revenus pour l'instant</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="navigation">
                    {{ knp_pagination_render(pagination) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/revenu/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Revenu{% endblock %}

{% block body %}
    <div class="block-header">
        <div class="row clearfix">
            <div class="col-md-6 col-sm-12">
                <h2>Nouveau Revenu</h2>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-xl-9 col-lg-8 col-md-7">
                <div class="card">
                    <div class="header">
                        <h2>Remplissez le formulaire</h2>
                    </div>
                    <div class="body">
                        {{ form_start(form) }}
                            <div class="row clearfix">
                                <div class="col-lg-12 col-md-12">
                                    <div class="form-group">
                                        {{ form_row(form.denomination,{
                                            label:false,
                                            attr:{
                                                "class":"form-control",
                                                "placeholder":"Dénomination"
                                            }
                                        }) }}
                                    </div>
                                </div>
                                <div class="col-lg-3 col-md-3">
                                    <div class="form-group">
                                        {{ form_row(form.amount, {
                                            label: false,
                                            attr:{
                                                "class":"form-control",
                                                "placeholder":"Montant"
                                            }
                                        }) }}
                                    </div>
                                </div>
                                <div class="col-lg-5 col-md-6">
                                    <div class="form-group">
                                        {{ form_row(form.submit_at, {
                                            label: false,
                                            attr:{
                                                "class":"form-control"
                                            }
                                        }) }}
                                    </div>
                                </div>
                                <br>
                                <button type="submit" class="btn btn-round btn-primary">Enregistrer</button>
                            </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a class="btn btn-primary" href="{{ path('revenu_index') }}">Retour à la liste</a>
{% endblock %}