src/Entity/Revenu.php
<?php

namespace App\Entity;

use App\Repository\RevenuRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=RevenuRepository::class)
 */
class Revenu
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $submit_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $denomination;

    /**
     * @ORM\Column(type="bigint")
	 * @Assert\GreaterThan(value=0, message="Entrer un montant superieur a zéro")
     */
    private $amount;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="revenus")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    public function __construct()
	{
		$this->submit_at = new \DateTime("now");
	}

	public function getId(): ?int
             {
                 return $this->id;
             }

    public function getSubmitAt(): ?\DateTimeInterface
    {
        return $this->submit_at;
    }

    public function setSubmitAt(\DateTimeInterface $submit_at): self
    {
        $this->submit_at = $submit_at;

        return $this;
    }

    public function getDenomination(): ?string
    {
        return $this->denomination;
    }

    public function setDenomination(string $denomination): self
    {
        $this->denomination = $denomination;

        return $this;
    }

    public function getAmount(): ?string
    {
        return $this->amount;
    }

    public function setAmount(string $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Bienvenue!{% endblock %}</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{{ asset('vendor/bootstrap/css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ asset('vendor/font-awesome/css/font-awesome.min.css') }}">
        <link rel="stylesheet" href="{{ asset('assets/css/site.min.css') }}">
        {% block stylesheets %}{% endblock %}
    </head>
    <body class="theme-blue">

    <!-- Overlay For Sidebars -->
    <div class="overlay"></div>

    <div id="wrapper">

        <nav class="navbar navbar-fixed-top">
            <div class="container-fluid">

                <div class="navbar-left">
                    <div class="navbar-brand">
                        <a class="small_menu_btn" href="javascript:void(0);"><i class="fa fa-align-left"></i></a>
                        <a href="index.html"><span>Gestion des finances</span></a>
                    </div>
                </div>

                <div class="navbar-right">
                    <div id="navbar-menu">
                        <ul class="nav navbar-nav">
                            {% if not app.user %}
                                <li><a href="{{ path('app_login') }}" class="icon-menu">Connexion</a></li>
                                <li><a href="{{ path('app_register') }}" class="icon-menu">S'inscrire</a></li>
                            {% else %}
                                <li class="active"><a disabled style="cursor:default;" class="icon-menu active">Solde : {{ app.user.solde }} FCFA</a></li>
                                <li><a href="{{ path('app_logout') }}" class="icon-menu">Déconnexion</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </nav>

        <div id="left-sidebar" class="sidebar">
            <div class="sidebar_list">
                <div class="tab-content" id="main-menu">
                    <div class="tab-pane active" id="Home-icon">
                        <nav class="sidebar-nav sidebar-scroll">
                            <ul class="metismenu">
                                {% if app.user %}
                                    <li class="active"><a><i class="fa fa-user"></i><span>{{ app.user.username }}</span></a></li>
                                {% endif %}
                                <li class="header">Revenus</li>
                                <li class="{% if active is defined and active == "consultation" %} active {% endif %}"><a href="{{ path('revenu_index') }}"><i class="fa fa-arrow-down"></i><span>Consulter les revenus</span></a></li>
                                <li class="{% if active is defined and active == "new_consultation" %} active {% endif %}"><a href="{{ path('revenu_new') }}"><i class="fa fa-plus"></i><span>Enregistrer un revenu</span></a></li>

                                <li class="header">Dépenses</li>
                                <li class="{% if active is defined and active == "depense" %} active {% endif %}"><a href="{{ path('depense_index') }}"><i class="fa fa-arrow-up"></i><span>Consulter les dépenses</span></a></li>
                                <li class="{% if active is defined and active == "depense_new" %} active {% endif %}"><a href="{{ path('depense_new') }}"><i class="fa fa-plus"></i><span>Enregistrer une dépense</span></a></li>

                                <li class="mt-4 {% if active is defined and active == "solde" %} active {% endif %}"><a href="{{ path('home') }}"><i class="fa fa-dollar"></i><span>Consulter le solde</span></a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>

        <div id="main-content">
            {% block body %}

            {% endblock %}
        </div>

    </div>

    <!-- Javascript -->
    <!-- Latest jQuery -->
    <script src="{{ asset('vendor/jquery/jquery-3.3.1.min.js') }}"></script>

    <!-- Bootstrap 4x JS  -->
    <script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <!-- Project Common JS -->
    <script src="{{ asset('assets/js/common.js') }}"></script>
    <script src="{{ asset('assets/js/index.js') }}"></script>
    {% block javascripts %}{% endblock %}
    </body>
</html>